// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TraceClient is the client API for Trace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceClient interface {
	Consume(ctx context.Context, in *TraceData, opts ...grpc.CallOption) (*Reply, error)
}

type traceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceClient(cc grpc.ClientConnInterface) TraceClient {
	return &traceClient{cc}
}

func (c *traceClient) Consume(ctx context.Context, in *TraceData, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/data.Trace/Consume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceServer is the server API for Trace service.
// All implementations must embed UnimplementedTraceServer
// for forward compatibility
type TraceServer interface {
	Consume(context.Context, *TraceData) (*Reply, error)
	mustEmbedUnimplementedTraceServer()
}

// UnimplementedTraceServer must be embedded to have forward compatible implementations.
type UnimplementedTraceServer struct {
}

func (UnimplementedTraceServer) Consume(context.Context, *TraceData) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedTraceServer) mustEmbedUnimplementedTraceServer() {}

// UnsafeTraceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceServer will
// result in compilation errors.
type UnsafeTraceServer interface {
	mustEmbedUnimplementedTraceServer()
}

func RegisterTraceServer(s grpc.ServiceRegistrar, srv TraceServer) {
	s.RegisterService(&Trace_ServiceDesc, srv)
}

func _Trace_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data.Trace/Consume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServer).Consume(ctx, req.(*TraceData))
	}
	return interceptor(ctx, in, info, handler)
}

// Trace_ServiceDesc is the grpc.ServiceDesc for Trace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Trace",
	HandlerType: (*TraceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Consume",
			Handler:    _Trace_Consume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
