// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

const (
	Type            = "grpcclient"
	TracesStability = component.StabilityLevelDevelopment
)
